# Site settings
title: Data Science Africa, Accra
email: m.t.smith@sheffield.ac.uk
banner: "Balme_Library.JPG"
description: > # this means to ignore newlines until "baseurl:"
  The 2019 Data Science Africa summer school held in Accra.
baseurl: "/dsa2019accra" # the subpath of your site, e.g. /blog/
#url: "to do" # the base hostname & protocol for your site
twitter_username: datascienceafrica.org
logo_url: img/logo.png
github_username: datsciafrica
#facebook_page: gaussianprocesssummerschool

# youtube:
  # height: 315
  # width: 560

school:
  name: Data Science in Africa School
  location: Ashesi University, Ghana
  dates:
  - {date: 21, day: Monday, month: October, year: 2019}
  - {date: 22, day: Tuesday, month: October, year: 2019}
  - {date: 23, day: Wednesday, month: October, year: 2019}
  registration:
    deadline:
      date: 01
      month: July
      year: 2019
    open: False
  draft: Y # set to Y if the programme is draft only.

conference:
  hosts:
  organizers:
  - {name: Neil Lawrence, url: "http://inverseprobability.com"}
  - {name: Mike Smith, url: "http://www.michaeltsmith.org"}
  - {name: Ernest Mwebaze, url: "http://air.ug/~emwebaze"}
  - {name: Mubangizi Martin Gordon, url: "http://air.ug/~mmubangizi"}
  - {name: John Quinn, url: "http://air.ug/~jquinn"}
  - {name: Mike Croucher, url: "http://www.walkingrandomly.com"}
  name: Data Science in Africa Workshop 
  location: Ashesi University, Ghana
  year: 2019
  month: October
  registration
    deadline:
      date: 01
      month: July
      year: 2019
    open: False
  # add other days here for them to appear
  dates:	
  - {date: 24, day: Thursday, month: October, year: 2019}
  - {date: 25, day: Friday, month: October, year: 2019}
  draft: Y # set to Y if the programme is draft only.
  
# Hero
hero:
    # hero_img: hero.jpg
    hero_img: gazzelle.jpg
    hero_img2: 
    hero_title: Data Science
    hero_description: Conference website.

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

sass:
    sass_dir: _scss

# Build settings
markdown: kramdown

